Add payloadId to DB
aneoconsulting/ArmoniK.Core pull request #107
Opened 2022-07-12 07:21 UTC by jfonseca-aneo

Fix https://github.com/aneoconsulting/ArmoniK/issues/163

2022-07-13 07:05 UTC, aneojgurhem requested changes

2022-07-13 07:05 UTC, aneojgurhem commented on Adaptors/Memory/src/TaskTable.cs
> +                                   newTaskRetryOfIds.First(),
taskData.PayloadId ?

2022-07-13 07:05 UTC, aneojgurhem commented on Adaptors/MongoDB/src/TaskTable.cs
> +                                   newTaskRetryOfIds.First(),
idem

2022-07-13 07:05 UTC, aneojgurhem commented on Common/src/Storage/TaskData.cs
> +           taskId,
Je ne suis pas convaincu que ce soit le bon endroit pour faire en sorte que PayloadId soit le task Id. J'aurais plutot vu ça dans la creation de la tache.

2022-07-13 13:10 UTC, jfonseca-aneo commented on Adaptors/Memory/src/TaskTable.cs
> +                                   newTaskRetryOfIds.First(),
updated!

2022-07-18 09:07 UTC, aneojgurhem requested changes

2022-07-18 09:07 UTC, aneojgurhem commented on Common/src/Storage/TaskData.cs
> +                       string        RetryBaseId,
Je pensais plutot à un InitialTaskId

2022-07-18 09:07 UTC, aneojgurhem commented on Common/src/Storage/TaskData.cs
> +           Guid.NewGuid().ToString(),
Et du coup ce champ c'est le taskId et pas une valeur générée. L'idée c'était de garder le taskId initial et d'ajouter le nombre de retry au bout.
L'alternative serait de ne pas laisser la main à l'utilisateur de créer son propre id. Il devrait être généré lors de la création des taches. Mais c'est un peu plus gros et l'objet d'une autre issue.

2022-07-18 09:07 UTC, aneojgurhem commented on Common/src/Storage/TaskData.cs
> +  }
Avec les remarques précédentes, cette fonction ne me semble pas nécessaire.

2022-07-18 09:49 UTC, jfonseca-aneo commented on Common/src/Storage/TaskData.cs
> +  }
nous en aurons toujours besoin pour le PayloadId

2022-07-18 09:50 UTC, jfonseca-aneo commented on Common/src/Storage/TaskData.cs
> +           Guid.NewGuid().ToString(),
d'acc

2022-07-18 17:51 UTC, aneojgurhem approved these changes

2022-07-18 17:52 UTC, merged