LinkCredit parameter to control prefetching
aneoconsulting/ArmoniK.Core pull request #118
Opened 2022-08-04 12:42 UTC by jfonseca-aneo

2022-08-07 21:34 UTC, aneojgurhem commented on Adaptors/Amqp/src/QueueStorage.cs
> +                           true);
Je l'aurais mis à la creation du receiver

2022-08-08 05:44 UTC, aneojgurhem requested changes

2022-08-08 05:44 UTC, aneojgurhem commented on Adaptors/Amqp/src/Options/Amqp.cs
> +  public string? CaPath            { get; set; }
Je ne suis pas sur que ce soit le moment d'ajouter les ?. ça a l'air d'ajouter pas mal de warnings en plus.

2022-08-08 07:00 UTC, jfonseca-aneo commented on Adaptors/Amqp/src/Options/Amqp.cs
> +  public string? CaPath            { get; set; }
à cause du `nullable,`  j'ai eu plus warnings sans les `?`

2022-08-08 07:20 UTC, jfonseca-aneo commented on Adaptors/Amqp/src/QueueStorage.cs
> +                           true);
Je ne suis pas sur, il faudra que je mets un `await`  immédiatement après l'`asyncLazy` pour faire ça

2022-08-08 12:30 UTC, jfonseca-aneo commented on Adaptors/Amqp/src/QueueStorage.cs
> +                           true);
Changé

2022-08-08 12:31 UTC, jfonseca-aneo commented on Adaptors/Amqp/src/Options/Amqp.cs
> +  public string? CaPath            { get; set; }
je vais le corriger dans une outre pr

2022-08-08 12:48 UTC, aneojgurhem approved these changes

2022-08-08 13:16 UTC, merged