one queue per partition
aneoconsulting/ArmoniK.Core pull request #128
Opened 2022-08-11 15:19 UTC by jfonseca-aneo

2022-08-12 06:06 UTC, aneojgurhem requested changes

2022-08-12 06:06 UTC, aneojgurhem commented on Adaptors/Amqp/src/QueueStorage.cs
> +        Console.WriteLine(receiver.Name);
log ?

2022-08-12 06:06 UTC, aneojgurhem commented on Adaptors/Amqp/tests/QueueStorageTests.cs
> +                                            "part1",
use the defined variable

2022-08-12 06:06 UTC, aneojgurhem commented on Common/src/Pollster/Pollster.cs
> +    partitionId_           = "defaultPartition";
This should be the partition id from the Amqp Options

2022-08-12 09:12 UTC, aneojgurhem approved these changes

2022-08-22 08:37 UTC, aneojgurhem commented on Adaptors/Amqp/src/ServiceCollectionExt.cs
> +//
il y a un warning nullable

2022-08-22 08:39 UTC, aneojgurhem submitted a review, later dismissed

2022-08-23 06:36 UTC, aneojgurhem commented on Control/PartitionMetrics/src/Properties/launchSettings.json
> +{
It is not necessary to keep it since it is the default one.

2022-08-23 10:59 UTC, aneojgurhem requested changes

2022-08-23 10:59 UTC, aneojgurhem commented on Common/src/Storage/IQueueStorageBase.cs
> +                            string              partitionId,
This should not be necessary

2022-08-23 11:03 UTC, aneojgurhem approved these changes

2022-08-23 11:03 UTC, jfonseca-aneo commented on Common/src/Storage/IQueueStorageBase.cs
> +                            string              partitionId,
indeed the whole class is not necessary

2022-08-23 11:30 UTC, merged