Have a maximum allowed number of errors before crashing
aneoconsulting/ArmoniK.Core pull request #156
Opened 2022-10-03 06:26 UTC by lemaitre-aneo

Without this, pods can loop on errors. If too many errors are detected, no matter what the healthcheck is saying, the pod will be marked unhealthy and stop.

2022-10-03 06:38 UTC, aneojgurhem requested changes

2022-10-03 06:38 UTC, aneojgurhem commented on Common/src/Pollster/Pollster.cs
> +              logger_.LogError("Too many consecutive errors in MainLoop. Stopping processing");
Il manque un test pour ça dans PollsterTest

2022-10-03 06:38 UTC, aneojgurhem commented on Common/src/Pollster/Pollster.cs
> +  private const    int                        maxErrorAllowed = 10;
Il faudrait que ce soit paramétrable et qu'on puisse le mettre à 0 pour les cas où comme dans docker-compose, il n'y a ni health check ni restart de pod.
Il y a une classe d'option nommée Pollster. Je pense qu'on peut la mettre dans cette classe.

2022-10-03 06:38 UTC, aneojgurhem commented on Common/tests/Pollster/TaskHandlerTest.cs
>    [TestCaseSource(nameof(TestCaseOuptut))]
Du coup, il manque peut être des tests dans cette source de tests. Il n'était peut être pas nécessaire de mettre le `ExceptionWorkerStreamHandler` public ni de changer le type en input du test.

2022-10-03 06:40 UTC, lemaitre-aneo commented on Common/src/Pollster/Pollster.cs
> +              logger_.LogError("Too many consecutive errors in MainLoop. Stopping processing");
Oui, j'y travaille.

2022-10-03 06:41 UTC, lemaitre-aneo commented on Common/src/Pollster/Pollster.cs
> +  private const    int                        maxErrorAllowed = 10;
Il suffit de le mettre dans le constructeur pour qu'il soit accessible par l'injection de dépendance ?

2022-10-03 06:42 UTC, lemaitre-aneo commented on Common/tests/Pollster/TaskHandlerTest.cs
>    [TestCaseSource(nameof(TestCaseOuptut))]
J'ai du changer le type d'input de test pour pouvoir accéder au type d'erreur renvoyer, et m'assurer que c'est bien celle-là qui est renvoyée. Je ne vois pas comment faire autrement qu'en explicitant le type d'entrée. Et pour se faire, il faut que le type lui-même soit public.

2022-10-03 06:45 UTC, aneojgurhem commented on Common/src/Pollster/Pollster.cs
> +  private const    int                        maxErrorAllowed = 10;
C'est déjà fait, il faut juste ajouter l'option et mettre une valeur par défaut. Et je pense que cette valeur doit être 0 et il faudra mettre quelque chose de positif pour l'infra

2022-10-03 06:50 UTC, aneojgurhem commented on Common/tests/Pollster/TaskHandlerTest.cs
>    [TestCaseSource(nameof(TestCaseOuptut))]
Ok. Il me semblait que les tests ne prenait pas de <> en entrée.

2022-10-03 06:59 UTC, aneojgurhem commented on Common/src/Pollster/Pollster.cs
> +            if (pollsterOptions_.MaxErrorAllowed >= 0 && consecutiveErrors >= pollsterOptions_.MaxErrorAllowed)
What if 0 ? Never working ?

2022-10-03 13:19 UTC, aneojgurhem commented on Common/src/Pollster/Pollster.cs
> +        catch (TooManyException e)
tu peux enlever le e quand tu ne te sers pas de l'exception, et ça enlève un warning^^

2022-10-03 14:49 UTC, aneojgurhem requested changes

2022-10-03 14:49 UTC, aneojgurhem commented on Common/src/Injection/Options/Submitter.cs
> +  public int maxErrorAllowed { get; set; } = 5;
Manque un M maj

2022-10-03 14:49 UTC, aneojgurhem commented on Common/src/Pollster/Pollster.cs
> +  public bool Failed { get; private set; }
Pour aider dans les tests ?

2022-10-03 14:49 UTC, aneojgurhem commented on Common/src/gRPC/ExceptionInterceptor.cs
> +    Console.WriteLine($"Interceptor HealthCheck: errors {nbErrors_}/{maxAllowedErrors_}");
logger !

2022-10-03 15:31 UTC, aneojgurhem approved these changes

2022-10-04 13:02 UTC, aneojgurhem approved these changes

2022-10-04 15:08 UTC, merged