Added more documentation for auth
aneoconsulting/ArmoniK.Core pull request #167
Opened 2022-10-17 17:02 UTC by dbrasseur-aneo

Fix https://github.com/aneoconsulting/ArmoniK/issues/616

2022-10-17 17:22 UTC, aneojgurhem requested changes

2022-10-17 17:22 UTC, aneojgurhem commented on Common/src/Auth/Authorization/AuthorizationPolicyProvider.cs
> +  /// <returns></returns>
idem

2022-10-17 17:22 UTC, aneojgurhem commented on Common/src/Auth/Authorization/AuthorizationPolicyProvider.cs
> +  /// <returns></returns>
idem

2022-10-17 17:22 UTC, aneojgurhem commented on Common/src/Auth/Authorization/Permissions.cs
> +  /// <returns></returns>
no returns

2022-10-19 06:48 UTC, aneojgurhem requested changes

2022-10-19 06:48 UTC, aneojgurhem commented on Common/src/Auth/Authorization/AuthorizationPolicyProvider.cs
> +  ///   Get an authorization policy accepting accepting anything
accepting x2

2022-10-19 07:02 UTC, dbrasseur-aneo commented on Common/src/Auth/Authorization/AuthorizationPolicyProvider.cs
> +  ///   Get an authorization policy accepting accepting anything
```suggestion
  ///   Get an authorization policy accepting anything
```

2022-10-19 07:15 UTC, aneojgurhem approved these changes

2022-10-19 08:47 UTC, merged