chore: Use bytes type for tosend as log_message and Add logging module
aneoconsulting/ArmoniK.Core pull request #491
Opened 2023-09-06 16:14 UTC by jeremyzyngeraneo

2023-09-06 20:17 UTC, aneojgurhem requested changes

2023-09-06 20:17 UTC, aneojgurhem commented on tools/logs2seq.py
> +def process_json_log(url, file_name: IO[bytes]):
```suggestion
def process_json_log(url: str, file_name: str):
```

2023-09-06 20:59 UTC, aneojgurhem commented on tools/logs2seq.py
> +                log_message = bytes(line, "utf-8")
```suggestion
                log_message = bytes(line + "\n", "utf-8")
```

2023-09-11 09:03 UTC, aneojgurhem requested changes
```python
                parsed = json.loads(line)
                if "@t" not in parsed:
                    continue
```

We need to check that there is this field because if the field is not present the data are not accepted. Can you add it ?

2023-09-11 11:55 UTC, jeremyzyngeraneo commented
`if line.startswith("{\"@t"):`

Is it possible to filter the data like this ?

2023-09-11 12:24 UTC, aneojgurhem commented
No `@t` can be anywhere in the document

2023-09-11 14:44 UTC, aneojgurhem approved these changes

2023-09-12 14:27 UTC, merged