Tests for IResultTable
aneoconsulting/ArmoniK.Core pull request #5
Opened 2022-03-10 13:49 UTC by jfonseca-aneo

2022-03-10 13:58 UTC, jfonseca-aneo commented
resolves aneoconsulting/ArmoniK#80

2022-03-16 08:44 UTC, aneojgurhem requested changes

2022-03-16 08:44 UTC, aneojgurhem commented on Adaptors/Memory/src/ResultTable.cs
> +        throw new ArmoniKException("Key already exists");
Est ce que tu peux ajouter quelle clé n'est pas trouvée ?

2022-03-16 08:44 UTC, aneojgurhem commented on Adaptors/MongoDB/tests/ResultTableTests.cs
> +      { $"{Options.MongoDB.SettingSection}:{nameof(Options.MongoDB.Port)}", uri.Port.ToString() },
Je crois que ces deux instructions ne sont pas nécessaires

2022-03-16 08:44 UTC, aneojgurhem commented on Common/tests/IResultTableTests.cs
> +    //TODO: Write a test for the case in which a non existing Id is given.
TODO !

2022-03-16 09:16 UTC, jfonseca-aneo commented on Adaptors/Memory/src/ResultTable.cs
> +        throw new ArmoniKException("Key already exists");
ajoutée

2022-03-16 09:16 UTC, jfonseca-aneo commented on Adaptors/MongoDB/tests/ResultTableTests.cs
> +      { $"{Options.MongoDB.SettingSection}:{nameof(Options.MongoDB.Port)}", uri.Port.ToString() },
Ok, je las effacerais

2022-03-16 09:20 UTC, aneojgurhem approved these changes

2022-03-16 09:20 UTC, merged