feat: Added a python script utility to import logs stored in an S3 bucket to Seq
aneoconsulting/ArmoniK.Core pull request #799
Opened 2024-11-18 15:11 UTC by AncientPatata

# Motivation

This PR is related to the work done to [export logs from localhost to an S3 bucket](https://github.com/aneoconsulting/ArmoniK.Infra/pull/187). Adding a more general script to import saved ArmoniK logs from previous runs to a Seq deployment for further analysis. 

# Description

Building on the log2seq.py script from #62, generalized it to download entire directories that you can freely specify to match the new exports.

# Testing

Multiple test runs of the script.

# Impact

Not applicable.

# Additional Information

[Any additional information that reviewers should be aware of.]

# Checklist

- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] I have thoroughly tested my modifications and added tests when necessary.
- [ ] Tests pass locally and in the CI.
- [x] I have assessed the performance impact of my modifications.

2024-11-18 15:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aneoconsulting/ArmoniK.Core?pullRequest=799) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aneoconsulting/ArmoniK.Core?pullRequest=799) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aneoconsulting/ArmoniK.Core?pullRequest=799) it.</sub>

2024-11-19 17:13 UTC, qdelamea-aneo requested changes

2024-11-19 17:13 UTC, qdelamea-aneo commented on tools/s3_to_seq/s3_to_seq.py
> +        """
Move the docstring after the class definition.

2024-11-19 17:13 UTC, qdelamea-aneo commented on tools/s3_to_seq/s3_to_seq.py
> +def main(args: argparse.Namespace):
Do not use argument namespace as function input. Instead list arguments and then call the function using **args to unpack the namespace.

2024-11-19 17:13 UTC, qdelamea-aneo commented on tools/s3_to_seq/s3_to_seq.py
> +        except Exception:
When handling exceptions you must always catch precise exceptions. Here you catch any exception even if it its not related to the client creation (like SIGTERM). So replace with the precise exeption(s) you wan to catch.

2024-11-21 19:27 UTC, aneojgurhem reviewed
code is great but I would have expected to see this in ArmoniK instead of ArmoniK.Core

2024-11-26 11:13 UTC, AncientPatata commented
> code is great but I would have expected to see this in ArmoniK instead of ArmoniK.Core

Moving it

2024-11-26 11:13 UTC, closed without merging